[build]
base = "netlify"
publish = "public"
command = "node_modules/.bin/antora --clean --fetch ../production-antora-playbook.yml"

[build.environment]
NODE_VERSION = "10"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

#[context.production.environment]
#ALGOLIA_API_KEY = "..."
#ALGOLIA_INDEX_NAME = "asciidoctor"
#GOOGLE_ANALYTICS_KEY = "..."

[context.deploy-preview]
command = "node_modules/.bin/antora --clean --fetch ../production-antora-playbook.yml"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
