site:
  title: Antora Demo
  url: https://janiveer.github.io/antora-demo
  start_page: home::index.adoc
content:
  branches: HEAD
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/janiveer/lightweight-markup.git
    branches: [antora-demo-v1, antora-demo-v2]
    start-path: home
  - url: https://github.com/janiveer/xml-to-json.git
    branches: [antora-demo]
    start-path: antora
  - url: https://github.com/janiveer/Flecty.git
    branches: [antora-demo-v1, antora-demo-v2]
    start-path: docs
  - url: https://github.com/janiveer/Vigenere.git
    branches: [antora-demo-v1, antora-demo-v2]
    start-path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
  extensions:
  - ./lib/json-config-ui-block-macro.js
  - ./lib/man-inline-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public
